#!/usr/bin/env bash
# Configures a new HAProxy as a load balancer

# Install HAProxy on the server
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.*

# Configure HAProxy to distribute requests using a round-robin algorithm
echo '
frontend sammykingx.tech
        bind 0.0.0.0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 806573-web-01 54.209.16.146:80 check
        server 806573-web-02 54.146.85.153:80 check
' | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart
